title: themuuj.com
description: Mad Machinations of a Software Architect
markdown: kramdown
theme: jekyll-theme-architect
linkedin_username: matthew-jackson
github_username: themuuj
plugins:
  - jekyll-feed
permalink: /:categories/:year/:month/:title/
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: default
      author: Matthew W. Jackson
      category: blog
